{
    "page": 1,
    "results": [
        {
            "adult": False,
            "backdrop_path": "/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
            "genre_ids": [28, 12, 14, 878],
            "id": 19995,
            "original_language": "en",
            "original_title": "Avatar",
            "overview": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
            "popularity": 98.204,
            "poster_path": "/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
            "release_date": "2009-12-15",
            "title": "Avatar",
            "video": False,
            "vote_average": 7.583,
            "vote_count": 31557,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [18],
            "id": 1096978,
            "original_language": "es",
            "original_title": "Avatar",
            "overview": "Tension mounts between a quadraplegic man and his wife as she prepares a bath for him.",
            "popularity": 3.826,
            "poster_path": "/gmnD2e1RvMdCl9D1rsDEQaQlJxK.jpg",
            "release_date": "2006-04-11",
            "title": "Avatar",
            "video": False,
            "vote_average": 6.4,
            "vote_count": 46,
        },
        {
            "adult": False,
            "backdrop_path": "/mljnZyk8gwO2YH9EDC5SMy4XgeP.jpg",
            "genre_ids": [18, 14],
            "id": 1295181,
            "original_language": "it",
            "original_title": "Avatar",
            "overview": "Based on Théophile Gautier's novel of the same name, the film tells of the tragic love affair of Ottavio de Saville. He falls madly in love with Madame Prascovie Labinska, a woman very faithful to her husband, the Polish count Olaf Labinski. Alarmed by the growing physical and mental weariness of the desperate young man, his relatives and friends decide to turn to Doctor Balthazar, who has just returned from a trip to the Indies where he was initiated into the secrets of Brahman.",
            "popularity": 0.899,
            "poster_path": "/nUTlHxnwomoIwojD0AF0OMzkonw.jpg",
            "release_date": "1916-03-06",
            "title": "Avatar",
            "video": False,
            "vote_average": 8.5,
            "vote_count": 1,
        },
        {
            "adult": False,
            "backdrop_path": "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
            "genre_ids": [878, 12, 28],
            "id": 76600,
            "original_language": "en",
            "original_title": "Avatar: The Way of Water",
            "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
            "popularity": 123.644,
            "poster_path": "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
            "release_date": "2022-12-14",
            "title": "Avatar: The Way of Water",
            "video": False,
            "vote_average": 7.62,
            "vote_count": 11971,
        },
        {
            "adult": False,
            "backdrop_path": "/uEwGFGtao9YG2JolmdvtHLLVbA9.jpg",
            "genre_ids": [99],
            "id": 111332,
            "original_language": "en",
            "original_title": "Avatar: Creating the World of Pandora",
            "overview": "The Making-of James Cameron's Avatar. It shows interesting parts of the work on the set.",
            "popularity": 12.911,
            "poster_path": "/d9oqcfeCyc3zmMal6eJbfj3gatc.jpg",
            "release_date": "2010-02-07",
            "title": "Avatar: Creating the World of Pandora",
            "video": False,
            "vote_average": 6.6,
            "vote_count": 154,
        },
        {
            "adult": False,
            "backdrop_path": "/fCK2T5ruQrqRsciJ01jjQSkNWVq.jpg",
            "genre_ids": [16, 28, 18],
            "id": 613200,
            "original_language": "zh",
            "original_title": "全职高手之巅峰荣耀",
            "overview": "In this prequel to the animated series The King's Avatar, Ye Xiu enters into the pro gaming world of Glory, and competes in the first Pro League series tournament.",
            "popularity": 6.995,
            "poster_path": "/6lyXW6GC7ruwDmhvEcRd9d46ZO7.jpg",
            "release_date": "2019-08-16",
            "title": "The King's Avatar: For the Glory",
            "video": False,
            "vote_average": 6.9,
            "vote_count": 56,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [99, 878],
            "id": 100287,
            "original_language": "da",
            "original_title": "Min Avatar og mig",
            "overview": "is a creative documentary-fiction film and a film that might expand your sense of reality. It is the story about a man who enters the virtual world Second Life to pursue his personal dreams and ambitions. His journey into cyberspace becomes a magic learning experience, which gradually opens the gates to a much larger reality.",
            "popularity": 2.249,
            "poster_path": "/dZCj0jiOoDzAzbQM7ryYFEjkjs7.jpg",
            "release_date": "2010-11-10",
            "title": "My Avatar and Me",
            "video": False,
            "vote_average": 6.2,
            "vote_count": 14,
        },
        {
            "adult": False,
            "backdrop_path": "/agnESua8QxISkOERvs7td6BAesa.jpg",
            "genre_ids": [28, 18, 878],
            "id": 1092060,
            "original_language": "ja",
            "original_title": "暴太郎戦隊ドンブラザーズVSゼンカイジャー",
            "overview": 'Divided into three acts, the first act is about the Zenkaigers dealing with a new Kashiwa Mochi World and Zocks declares himself as "Kashiwa Mochi King", the ruler of Zenkaitopia?! In the second act, it\'s been a year since Taro left and the five companions continue to fight as a team with Jiro as their leader. Taro later regains his memories, only for his companions to ask him to leave the Donbrothers. In the final act, an incident caused the two worlds to connect, thus a full-throttle miracle battle between the two Super Sentai begins!',
            "popularity": 4.792,
            "poster_path": "/h5MwCuYy2EUv3AmD3d3E6AUYo90.jpg",
            "release_date": "2023-05-03",
            "title": "Avataro Sentai Donbrothers vs. Zenkaiger",
            "video": False,
            "vote_average": 5.6,
            "vote_count": 17,
        },
        {
            "adult": False,
            "backdrop_path": "/1ToHikA7BtTxMD4YGyuwBURyv2W.jpg",
            "genre_ids": [878, 12, 14],
            "id": 83533,
            "original_language": "en",
            "original_title": "Avatar: Fire and Ash",
            "overview": "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
            "popularity": 32.565,
            "poster_path": "/vDdFxksDMkUJjZXd00OKJfwXKre.jpg",
            "release_date": "2025-12-17",
            "title": "Avatar: Fire and Ash",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
        },
        {
            "adult": False,
            "backdrop_path": "/eoAvHxfbaPOcfiQyjqypWIXWxDr.jpg",
            "genre_ids": [99],
            "id": 1059673,
            "original_language": "en",
            "original_title": "Avatar: The Deep Dive - A Special Edition of 20/20",
            "overview": "An inside look at one of the most anticipated movie sequels ever with James Cameron and cast.",
            "popularity": 18.106,
            "poster_path": "/i367eMUXwj9LtNqrVlw1NXGRLx7.jpg",
            "release_date": "2022-12-13",
            "title": "Avatar: The Deep Dive - A Special Edition of 20/20",
            "video": False,
            "vote_average": 7.1,
            "vote_count": 75,
        },
        {
            "adult": False,
            "backdrop_path": "/r5Au1g6UQXXNl9hqwMFwOCIBlwB.jpg",
            "genre_ids": [],
            "id": 1132450,
            "original_language": "ja",
            "original_title": "暴太郎戦隊ドンブラザーズVS暴太郎戦隊ドンブリーズ",
            "overview": "The Avataro Sentai Donburies, which first appeared in Avataro Sentai Donbrothers' press conference gets a TTFC special!",
            "popularity": 2.413,
            "poster_path": "/9hiiML3NMC4Qj25V97XEYl7bVKw.jpg",
            "release_date": "2023-11-05",
            "title": "Avataro Sentai Donbrothers vs. Avataro Sentai Donburies",
            "video": False,
            "vote_average": 6.8,
            "vote_count": 5,
        },
        {
            "adult": False,
            "backdrop_path": "/wEjFjWu5yiHk6U5YV9kSnwdWwNO.jpg",
            "genre_ids": [53, 14, 27],
            "id": 677528,
            "original_language": "kn",
            "original_title": "ಅವತಾರ ಪುರುಷ: Part 1",
            "overview": "When a son of an Ayurveda scholar goes missing, he blames his sister and cuts all ties with her. When the latter's daughter decides to set things right with a devious plan, there seems to be more trouble waiting for the family.",
            "popularity": 5.045,
            "poster_path": "/gQ29E9Qy6z5ExsxnpgUTHfpZFO3.jpg",
            "release_date": "2022-05-06",
            "title": "Avatara Purusha: Part 1",
            "video": False,
            "vote_average": 5.3,
            "vote_count": 14,
        },
        {
            "adult": False,
            "backdrop_path": "/gO81IsgrhwUS6aChXCjnjFKUS3S.jpg",
            "genre_ids": [27],
            "id": 282908,
            "original_language": "ja",
            "original_title": "アバター",
            "overview": 'Michiko lost her dad in a car accident when she was 10 years old. After the car accident, Michiko has lived with her mother Kyoko. Michiko, now in her 2nd year of high school, gets a cell phone from her mother as a birthday present. Michiko is so excited to have her very first cell phone. Soon afterwards, she is forced into joining social networking site "AvaQ" by classmate, and queen of the classroom, Taeko.',
            "popularity": 2.048,
            "poster_path": "/xEAhV18F5Ej78qL0EneyPqa2a20.jpg",
            "release_date": "2011-04-30",
            "title": "Avatar",
            "video": False,
            "vote_average": 5.8,
            "vote_count": 19,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [35],
            "id": 926519,
            "original_language": "fr",
            "original_title": "L'Avatar botanique de mademoiselle Flora",
            "overview": "A young woman lives sadly in a small garrison town with a soldier. Little by little, won over by boredom, sadness, total inaction, she develops a relationship with plants and starts talking to plants.",
            "popularity": 1.249,
            "poster_path": "/jV7LWoQbwXplgdIbMvT4UB8O1E3.jpg",
            "release_date": "1965-05-05",
            "title": "The Botanical Avatar of Mademoiselle Flora",
            "video": False,
            "vote_average": 6.4,
            "vote_count": 18,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [10770, 18, 10751],
            "id": 155444,
            "original_language": "pl",
            "original_title": "Awatar, czyli zamiana dusz",
            "overview": 'Count Olgierd Łabiński lives with his beloved wife in Paris in a beautiful palace. The Countess recalls her stay in Florence and her insistent admirer Octavius \u200b\u200bde Saville. Soon, Octavius, arrives in Paris and calls for the famous Dr. Cherbonneau, suspected of being a charlatan.  Citing the teachings of the East, Cherbonneau offers the patient an "avatar", a reincarnation of the soul, which takes a different body...',
            "popularity": 1.108,
            "poster_path": "/1H3TikyAGBnl6RuVHPJql1HzxQC.jpg",
            "release_date": "1964-01-01",
            "title": "Avatar: The Exchange of Souls",
            "video": False,
            "vote_average": 5.6,
            "vote_count": 8,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [28, 35, 14, 53],
            "id": 1268164,
            "original_language": "kn",
            "original_title": "ಅವತಾರ ಪುರುಷ 2",
            "overview": "In a battle of mantras, Dharka and Brahma vie for the Trishanku Mani. But when Jois is found dead, the disturbed Ashta Dhigbandana alerts Dharka to the stone`s presence in the house. Now, a junior artist posing as the long-lost son must fight to save the family from the real son`s dark magic",
            "popularity": 1.866,
            "poster_path": "/qNNoxTqBjXJvxiDjC6R3PVH0XoQ.jpg",
            "release_date": "2024-04-05",
            "title": "Avatara Purusha 2",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [99],
            "id": 829860,
            "original_language": "zh",
            "original_title": "Hunan, l'autre monde d'Avatar",
            "overview": "How China's magical Zhangjiajie National Park attracted director James Cameron, who came seeking inspiration for a mysterious fictional planet.",
            "popularity": 0.773,
            "poster_path": "/aCwF72gto2ADsQK28j7S9tE4xDa.jpg",
            "release_date": "2015-01-01",
            "title": "Hunan: The Other World of Avatar",
            "video": False,
            "vote_average": 5.8,
            "vote_count": 8,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [878, 12, 14],
            "id": 216527,
            "original_language": "en",
            "original_title": "Avatar 4",
            "overview": "The fourth installment of the Avatar franchise.",
            "popularity": 11.203,
            "poster_path": "/qzMYKnT4MG1d0gnhwytr4cKhUvS.jpg",
            "release_date": "2029-12-19",
            "title": "Avatar 4",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
        },
        {
            "adult": False,
            "backdrop_path": "/axSaeKvV5xF3zGYwXaSF8rUxaO1.jpg",
            "genre_ids": [99],
            "id": 183392,
            "original_language": "en",
            "original_title": "Capturing Avatar",
            "overview": "Capturing Avatar is a feature length behind-the-scenes documentary about the making of Avatar. It uses footage from the film's development, as well as stock footage from as far back as the production of Titanic in 1995. Also included are numerous interviews with cast, artists, and other crew members. The documentary was released as a bonus feature on the extended collector's edition of Avatar.",
            "popularity": 11.453,
            "poster_path": "/26SMEXJl3978dn2svWBSqHbLl5U.jpg",
            "release_date": "2010-11-16",
            "title": "Capturing Avatar",
            "video": False,
            "vote_average": 7.309,
            "vote_count": 81,
        },
        {
            "adult": False,
            "backdrop_path": None,
            "genre_ids": [12, 878, 14],
            "id": 393209,
            "original_language": "en",
            "original_title": "Avatar 5",
            "overview": "",
            "popularity": 10.073,
            "poster_path": "/rtmmvqkIC5zDMEd638Es2woxbz8.jpg",
            "release_date": "2031-12-17",
            "title": "Avatar 5",
            "video": False,
            "vote_average": 0.0,
            "vote_count": 0,
        },
    ],
    "total_pages": 4,
    "total_results": 79,
}