question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {
        "text": "Approximately one quarter of human bones are in the feet.",
        "answer": "True",
    },
    {
        "text": "The total surface area of a human lungs is the size of a football pitch.",
        "answer": "True",
    },
    {
        "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True",
    },
    {
        "text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
        "answer": "False",
    },
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {
        "text": "No piece of square dry paper can be folded in half more than 7 times.",
        "answer": "False",
    },
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
]

question_data2 = [
    {
        "response_code": 0,
        "results": [
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Japanese Anime &amp; Manga",
                "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "The Sun rises from the North.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "History",
                "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "In &quot;Undertale&quot;, the main character of the game is Sans.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Video Games",
                "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Film",
                "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "Entertainment: Video Games",
                "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Film",
                "question": "Actor Tommy Chong served prison time.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "Politics",
                "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science &amp; Nature",
                "question": "The planet Mars has two moons orbiting it.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science: Mathematics",
                "question": "An isosceles triangle has two sides of equal length as opposed to three.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Politics",
                "question": "Denmark has a monarch.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Video Games",
                "question": "During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "Codemasters is the developer of the Gran Turismo series.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science: Computers",
                "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "General Knowledge",
                "question": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "Science &amp; Nature",
                "question": "The chemical element Lithium is named after the country of Lithuania.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Cartoon &amp; Animations",
                "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Film",
                "question": "Sean Connery wasn&#039;t in &quot;Indiana Jones and the Kingdom of the Crystal Skull&quot; because he found retirement too enjoyable.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science: Mathematics",
                "question": "The proof for the Chinese Remainder Theorem used in Number Theory was NOT developed by its first publisher, Sun Tzu.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Art",
                "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Film",
                "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science &amp; Nature",
                "question": "Sugar contains fat.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "General Knowledge",
                "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Video Games",
                "question": "Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a picture of the Beslan school hostage crisis.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Sports",
                "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Geography",
                "question": "Greenland is almost as big as Africa.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "Entertainment: Japanese Anime &amp; Manga",
                "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Music",
                "question": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin Broadus, Jr.&#039;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "The color orange is named after the fruit.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Entertainment: Music",
                "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Geography",
                "question": "The flag of South Africa features 7 colours.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Music",
                "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "History",
                "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Sports",
                "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Politics",
                "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "The Lego Group was founded in 1932.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Video Games",
                "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Entertainment: Music",
                "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "Entertainment: Film",
                "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "History",
                "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland&#039;s.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science &amp; Nature",
                "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Geography",
                "question": "A group of islands is called an &#039;archipelago&#039;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
        ],
    }
]
